class_distribution:
  class_frequencies:
    bicycle: 292759
    building: 86292065
    bus: 3597425
    car: 53160326
    fence: 6695805
    motorcycle: 152285
    person: 1615520
    pole: 6008381
    rider: 134031
    road: 136585365
    sidewalk: 13212648
    sky: 112119788
    terrain: 6365408
    traffic light: 991457
    traffic sign: 2087668
    train: 102757
    truck: 6209633
    vegetation: 85976515
    wall: 3174881
  total_pixels: 524774717
  id_to_class:
    0: road
    1: sidewalk
    2: building
    3: wall
    4: fence
    5: pole
    6: traffic light
    7: traffic sign
    8: vegetation
    9: terrain
    10: sky
    11: person
    12: rider
    13: car
    14: truck
    15: bus
    16: train
    17: motorcycle
    18: bicycle
data:
  test_images: data/bdd100k/images/10k/test/
  train_images: data/bdd100k/images/10k/train/
  train_masks: data/bdd100k/labels/sem_seg/masks/train/
  val_images: data/bdd100k/images/10k/val/
  val_masks: data/bdd100k/labels/sem_seg/masks/val/
hyperparams:
  baseline:
    batch_size: 8
    epochs: 25
    hidden_dim: 128
    input_dim: 3
    lr: 0.001
    weight_decay: 0.0001
    num_classes: 19
runs:
  baseline: '1'
  u-net: '1'
transforms:
  flip: 0.5
  normalize:
    mean:
    - 0.3698435425758362
    - 0.41410791873931885
    - 0.4238499402999878
    std:
    - 0.24937671422958374
    - 0.26646897196769714
    - 0.2840002775192261
  resize:
  - 256
  - 448
