class_distribution:
  class_frequencies:
    bicycle: 292759
    building: 86292065
    bus: 3597425
    car: 53160326
    fence: 6695805
    motorcycle: 152285
    person: 1615520
    pole: 6008381
    rider: 134031
    road: 136585365
    sidewalk: 13212648
    sky: 112119788
    terrain: 6365408
    traffic light: 991457
    traffic sign: 2087668
    train: 102757
    truck: 6209633
    vegetation: 85976515
    wall: 3174881
  id_to_class:
    0: road
    1: sidewalk
    2: building
    3: wall
    4: fence
    5: pole
    6: traffic light
    7: traffic sign
    8: vegetation
    9: terrain
    10: sky
    11: person
    12: rider
    13: car
    14: truck
    15: bus
    16: train
    17: motorcycle
    18: bicycle
  total_pixels: 524774717
  color_map:
    0: [128, 64, 128]     # road
    1: [244, 35, 232]     # sidewalk
    2: [70, 70, 70]       # building
    3: [102, 102, 156]    # wall
    4: [190, 153, 153]    # fence
    5: [153, 153, 153]    # pole
    6: [250, 170, 30]     # traffic light
    7: [220, 220, 0]      # traffic sign
    8: [107, 142, 35]     # vegetation
    9: [152, 251, 152]    # terrain
    10: [70, 130, 180]    # sky
    11: [220, 20, 60]     # person
    12: [255, 0, 0]       # rider
    13: [0, 0, 142]       # car
    14: [0, 0, 70]        # truck
    15: [0, 60, 100]      # bus
    16: [0, 80, 100]      # train
    17: [0, 0, 230]       # motorcycle
    18: [119, 11, 32]     # bicycle
classes_to_transform:
  classes_to_combine:
    3: [4]
    11: [12]
    13: [14, 15]
  classes_to_exclude: [16]

data:
  test_images: data/bdd100k/images/10k/test/
  test_masks: data/bdd100k/labels/sem_seg/masks/test/
  train_images: data/bdd100k/images/10k/train/
  train_masks: data/bdd100k/labels/sem_seg/masks/train/
  val_images: data/bdd100k/images/10k/val/
  val_masks: data/bdd100k/labels/sem_seg/masks/val/
hyperparams:
  baseline:
    batch_size: 8
    epochs: 25
    hidden_dim: 128
    input_dim: 3
    lr: 0.001
    num_classes: 19
    weight_decay: 0.0001
  unet:
    base_channels: 64
    batch_size: 2
    epochs: 150
    in_channels: 3
    lr: 0.001
    num_classes: 19
    weight_decay: 0.0001
runs:
  baseline: '2'
  unet: '1'
transforms:
  flip: 0.5
  max_scale: 1.0
  min_scale: 0.35
  normalize:
    mean:
    - 0.3698435425758362
    - 0.41410791873931885
    - 0.4238499402999878
    std:
    - 0.24937671422958374
    - 0.26646897196769714
    - 0.2840002775192261
  og_scale:
  - 720
  - 1280
  resize:
  - 368 #divisible by 16, have to see how much we are downsampling
  - 640
